blank_issues_enabled: false
contact_links:
  - name: ğŸ› ï¸ General Questions & Support
    url: https://github.com/TundraSoft/tundra-connect/discussions
    about: Ask questions and discuss general topics related to Tundra Connect
